
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 17 2025 15:22:15 IST (Mar 17 2025 09:52:15 UTC)

// Verification Directory fv/fulladd 

module fulladd(a, b, c_in, c_out, sum);
  input [3:0] a, b;
  input c_in;
  output c_out;
  output [3:0] sum;
  wire [3:0] a, b;
  wire c_in;
  wire c_out;
  wire [3:0] sum;
  wire n_0, n_2, n_4;
  ADDFXL g335__2398(.A (a[3]), .B (b[3]), .CI (n_4), .CO (c_out), .S
       (sum[3]));
  ADDFX1 g336__5107(.A (b[2]), .B (a[2]), .CI (n_2), .CO (n_4), .S
       (sum[2]));
  ADDFX1 g337__6260(.A (b[1]), .B (a[1]), .CI (n_0), .CO (n_2), .S
       (sum[1]));
  ADDFX1 g338__4319(.A (b[0]), .B (a[0]), .CI (c_in), .CO (n_0), .S
       (sum[0]));
endmodule

